### ISSUE TITLE
Create rails upgrade checklist

### ISSUE THREAD

**Issue by skkprogress** [chef/chef#11780]

**Comment by skkprogress** [comment]
- [ ] Audit of supermarket and manage repos

- [ ] Document detailing what are the broad areas to be focussed on for upgrade

- [ ] List of red flags

- [ ] Milestones based upgrade plan

**Comment by skkprogress** [comment]
Issue moved to [chef/supermarket #2040](https://github.com/chef/supermarket/issues/2040) via [**ZenHub**](https://www.zenhub.com/)
