### ISSUE TITLE
Upgrade to Ruby 3.1

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef#12436]
TODO:
- [ ] mixlib-cli, config, auth...
- [ ] client tests
- [ ] omnibus builds
- [x] omnibus toolkit is decoupled
- [ ] knife

Acceptance Criteria:
- [ ] Should support Ruby 3.0 and 3.1 (do we need n-1 support?)

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/corefoundation/pull/31
