### ISSUE TITLE
Merge knife-opc into core Chef

### ISSUE THREAD

**Issue by stevendanna** [chef/chef#3517]
All standard API endpoints should be accessible via core Chef without additional plugins. With the addition of the `knife user` commands, nearly half of `knife-opc` is now unnecessary.  The following is a list of items that would likely be needed to be addressed or investigated to make that happen:
- [x] Support globally listing users: https://github.com/chef/chef/issues/3513
- [x] Support user-friendly error checking on file permissiosn: https://github.com/chef/chef/issues/3514
- [x] Support listing a user's organization membership: https://github.com/chef/chef/issues/3515
- [x] Add `knife org` subcommands: https://github.com/chef/chef/issues/3516
- [ ] Determine which supported versions (if any) require explicit user dissociation(https://github.com/chef/knife-opc/blob/master/lib/chef/knife/opc_user_delete.rb#L33-L39)
- [x] Determine if `knife user edits`'s private_key handling on update is correct for all supported Server versions (knife-opc does the following: https://github.com/chef/knife-opc/blob/master/lib/chef/knife/opc_user_delete.rb#L33-L39)
- [x] Determine if the `--orgname` flag to `knife opc user create` would be useful to port to `knife user create` (https://github.com/chef/knife-opc/blob/master/lib/chef/knife/opc_user_create.rb#L29-L32). 
- [x] Determine if `knife user password` command should be moved to core chef (https://github.com/chef/knife-opc/blob/master/lib/chef/knife/opc_user_password.rb)

**Comment by snehaldwivedi** [comment]
@stevendanna can you please elaborate `Determine which supported versions (if any) require explicit user dissociation(https://github.com/chef/knife-opc/blob/master/lib/chef/knife/opc_user_delete.rb#L33-L39)`  ?

**Comment by stevendanna** [comment]
@snehaldwivedi Apologies but I don't think I am going to remember the full details of a comment I made 5 years ago.  However, looking at the opc_user_delete code, we have a large amount of code that gets all of the organizations for the user and then dissociates the user from each of those organizations before deleting them:

https://github.com/chef/knife-opc/blob/master/lib/chef/knife/opc_user_delete.rb#L50-L69

which was explicitly added by support:

https://github.com/chef/knife-opc/pull/6

from Slack it appears this was added as a result of a support ticket.  That support ticket is in an older support ticketing system, but I have a partial email record of the ticket.  As part of that ticket, the user was concerned with dangling references to a now deleted user:

> a concern was raised here that removing the users without disassociating them might leave dangling references and cause problems further on; Apparently we have run into this issue before.  Just wanted to double check with you before doing anything.

My _strong_ suspicion is that it is possible (likely even) that the issue being referred to was in an ancient version of Chef Server that ran against a completely different database (CouchDB) than the current server.  In the current server, deleting a user should cause a cascading deleting into the org_user_associations table.

However, all that said, this code has been working well for people without issue and it has subsequently gained various client-side validation features to prevent users from making a few common mistakes, so I think you can safely ignore the comment for now and preseve the current feature.
