### ISSUE TITLE
Chef 13 deprecation checklist

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3705]
This is intended to be a living list of all the things we want to change for the next major rev when we can break compat (though doing so should be carefully considered or Adam will be sad):
- [x] Remove resource cloning.
- [x] Remove `%{file}` from verification command path interpolation.
- [x] Remove old `partial_search` API.
- [x] Remove deprecated setters on `RunContext`.
- [x] Remove `Resource.dsl_name`.
- [x] Remove `Resource.provider_base`.
- [x] Remove `Resource::Execute#path`.
- [x] Remove setting LWRPs as consts.
- [x] Make `Resource::Script#code` required.
- [x] [Re-add freezing of resource property defaults](https://github.com/chef/chef/pull/3744).
- [x] [Make multiple default-y property values be an error](https://github.com/chef/chef/pull/3951).
- [x] Remove `knife cookbook site vendor`

**Comment by coderanger** [comment]
I've added the two I've been poking today, @chef/client-core what else should be on (or removed from) the list?

**Comment by coderanger** [comment]
Added some more from grepping for "will be removed" and similar.

**Comment by juliandunn** [comment]
Can I nominate `knife cookbook site vendor` and `knife cookbook test` commands?

**Comment by juliandunn** [comment]
Also wondering about all the deprecated classes in `lib/chef/deprecation`.

**Comment by lamont-granquist** [comment]
There's some other issues I cut against the Chef 13 milestone, plus there's spec tests that are designed to blow up once someone changes the version to 13.x.x.x.x

**Comment by thommay** [comment]
#5878

**Comment by coderanger** [comment]
Punting on `knife cookbook test` because it isn't deprecated and seems reasonable to keep for the moment, the rest of these are complete.
