### ISSUE TITLE
TODO to move chef-solo to use local-mode

### ISSUE THREAD

**Issue by thommay** [chef/chef#4567]
- [ ] chef-zero supports libraries with sub directories
- [ ] kill cookbook shadowing
- [ ] ruby roles and environments
- [ ] performance around cookbook loading

**Comment by coderanger** [comment]
* [ ] Make sure `Chef::Config[:solo]` is set.

**Comment by coderanger** [comment]
So thoughts on cookbook loading performance, Zero could add an extra bit of metadata on each file in the API with the actual underlying file path that Zero is serving from (if it exists, i.e. not full memory resident) and if the cookbook sync code sees that hint and the path exists and the hash matches, it uses it directly (symlink? hardlink?) rather than downloading the file over the API.

**Comment by lamont-granquist** [comment]
Yeah I think there's an open issue somewhere for the chef-zero server to just get its cookbooks out of the existing cookbook_path for the client and not do any copying-over-the-api at all...  I'm not even sure we'd need to symlink/hardlink, but just point chef-zero at the stuff we already have...

**Comment by lamont-granquist** [comment]
I updated the description to change 'kill site-cookbooks' to 'kill cookbook shadowing'

The difference is that 'site-cookbooks' just relies on cookbook_path being an Array.  I think we actually support that in ChefFS and/or we should fix ChefFS to support that.  We've never deprecated that formally.  Its kind of goofy, but people use it and while its annoying code it just sprinkles [ cookbook_path ].flatten around the codebase a bit.

The cookbook shadowing code is the awful stuff where you can have multiple versions of the apache cookbook in your cookbook path.  It is used to "union mount" cookbooks and override templates and files.  That's the thing that is deprecated, and which I'm fairly certain ChefFS cannot tractably support.  Users of that have to migrate to using a more chef-rewind kind of approach and/or just use better library cookbooks that are resource-based and allow for injecting custom templates (time to convert to the httpd cookbook from the apache cookbook).

**Comment by coderanger** [comment]
It has been aggressively deprecated since Chef 10, so I think we are clear to remove shadowing without a major version bump?

**Comment by lamont-granquist** [comment]
But chef-solo users don't run 'knife cookbook upload' and have not necessarily ever seen this deprecation warning.

I suspect if we just rip it out that chef-solo users will show up with pitchforks.

I *think* AWS has/had been using this feature:  http://docs.aws.amazon.com/opsworks/latest/userguide/cookbooks-101-opsworks-templates.html

I'm trying to figure out if that documentation broke when they (I think) switched to Chef 12/chef-zero instead of Chef 11/chef-solo?  I thought I recalled something about that, but I could be mistaken...

**Comment by lamont-granquist** [comment]
Welp, I'm confused.  I'm right that Chef 12 and Chef 11.10 on Opsworks uses zero:  http://docs.aws.amazon.com/opsworks/latest/userguide/cookbooks-101-opsworks-templates.html

Their 11.10 documentation on overriding cookbooks make it sound like they rolled their own cookbook shadowing:  http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-chef11-10.html#workingcookbook-chef11-10-override

**Comment by coderanger** [comment]
@lamont-granquist I agree, it sounds like something they built in their cookbook "compiler".

**Comment by thommay** [comment]
#4640

**Comment by thommay** [comment]
#4649

**Comment by lamont-granquist** [comment]
gonna call this one as done.

i think technically "performance around cookbook loading" is remaining but that is more the "why everyone still uses the legacy mode runner in chefspec tests" bug
