### ISSUE TITLE
Windows performance fixes EPIC

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#9075]
- [x] investigate ruby perf with systemtap (figuring out how to profile application dtrace/systemtap hooks)
- [ ] investigate profiling on windows with sysinternals
- [x] investigate why ruby stats files up to the root of the filesystem on every file it requires every single time (ruby patching).
- [x] merge https://github.com/chef/omnibus-software/pull/1113
- [x] ~~investigate changing omnibus-software back to using RubyInstaller and abandon source-code-built ruby~~
- [x] ~~investigate a way to precache gem library file paths on activation in appbundler binstubs (ruby patching)~~
- [ ] investigate monkeypatching a caching layer over require + gem install (e.g. faster_require)
- [ ] implement `chef exec` and `chef shell-init` in golang (chef.exe). https://github.com/chef/chef-workstation/issues/1505

Aha! Link: https://chef.aha.io/epics/CHEF-E-78

**Comment by lamont-granquist** [comment]
Based on investigation in #9076 the difference between our custom builds and RubyInstaller is not that great, and it may have come down to mostly that we were using -O2 (or only -O on 32-bit builds) vs. RubyInstaller using -O3.

**Comment by lamont-granquist** [comment]
Interesting prior art but its 6+ years out of date and written for ruby 1.9.x:

https://github.com/rdp/faster_require

The biggest perf hit comes from hitting this section in rubygems:

https://github.com/rubygems/rubygems/blob/2.7/lib/rubygems/core_ext/kernel_require.rb#L49-L55

Ultimately it is looping over these loops inside of ruby itself:

https://github.com/ruby/ruby/blob/5e22f873ed26092522f9bfc617d729bac88b284f/file.c#L6325-L6335

https://github.com/ruby/ruby/blob/5e22f873ed26092522f9bfc617d729bac88b284f/file.c#L6377-L6385

**Comment by mwrock** [comment]
I submitted https://github.com/chef/chef/pull/10383 which brings down `chef-client --version` on my windows laptop from an average 7.5 seconds to just under 3 second average on a warm file cache cache. The difference is more dramatic on a cold cache. Note: Windows has a magical file caching mechanism that caches recently accessed files for a certain amount of time. So the first invocation of `chef-client --version` will be much clower than the next. Like 3x slower.

Similar to @lamont-granquist my initial profiling observations showed all signs pointing to `require`. Eventually I found that patching `kernel#require` with:

```
puts "===============require #{path} -  #{(((Time.now) - start) * 1000).to_i}"
```

in its final `ensure` block where `start` was captured at the beginning of `require` gave an excellent picture of which libraries were eating up the largest chunks of time. So the above PR used `autoload` on the low hanging fruit. There were a few libraries that that continue to use require because of the way they monkey patch. For example `json` which consumes over 100ms to require also patches magically provides `Hash.to_json` so it is not a viable `autoload` candidate.

There are several libraries we are still requiring that take less that 50ms,. Collectively we could probably yield another second(?) if we went after all of them.

Another thing to consider is how we approach dynamic loading of resources and providers. Currently we need to `require` all of these. However, any single converge will likely use a small fraction. I believe we currently evaluate if a recipe resource symbol has been loaded. It seems like we could potentially change this approach so we did not need to load all resources and providers up front.

**Comment by lamont-granquist** [comment]
Yeah, I was thinking about resources and providers over the weekend.  But I think those all use require_relative which avoids the filesystem gem scanning so even if you lazy those it won't change much.  The improvement might be in downstream dependencies, but if we've done all this work downstream, then we should be autoloading stuff which is expensive, so shouldn't be seeing much of an improvement there either.

I could be incorrect about that, so it makes sense to double-check, but in my head-compiler it doesn't produce much of a perf increase.

**Comment by lamont-granquist** [comment]
I also started work on a gem to cache a manifest of all the files of all the gems installed in the system and use that instead of filesystem scanning, which I think will be the right solution to fixing this problem for good and getting really good cli perf everywhere.  It'll slighly break rubygems expectations (although you can still edit files, but you couldn't move them around or add new ones -- but i never do?  and doubt anyone else ever does?), and it'll slow down gem install / bundle install a bit, but it should produce a quantum jump up in loading perf across the board.

**Comment by tas50** [comment]
It seems like the path we should focus on optimizing is the knife codepath vs. the overall chef-client. If we could shave 2 seconds off the chef-client most people would notice that at all. Shaving 2 seconds of knife would be night and day though since that's all interactive and you generally issues dozens of those commands.

**Comment by lamont-granquist** [comment]
I'm going more down the path of "fix rubygems and make it all go away".

**Comment by phiggins** [comment]
> For example json which consumes over 100ms to require also patches magically provides Hash.to_json so it is not a viable autoload candidate.

I know this was just an arbitrary example, but could we disallow `Hash.to_json` and use autoload for it? It's not used in too many places:

```
Petes-MBP:chef pete$ grep -r "\.to_json\>" lib/ | grep -v "Chef::JSONCompat.to_json"
lib//chef/provider/package/snap.rb:            pdata = post_data.to_json.to_s
lib//chef/provider/package/snap.rb:          }.to_json
lib//chef/chef_fs/file_system/repository/base_file.rb:              data_handler.from_ruby(file_path).to_json
lib//chef/json_compat.rb:# We're requiring this to prevent breaking consumers using Hash.to_json
lib//chef/policy_builder/policyfile.rb:          to_h.to_json(*opts)
lib//chef/knife/core/windows_bootstrap_context.rb:          escape_and_echo(super.to_json)
lib//chef/knife/bootstrap/templates/windows-chef-client-msi.erb:  <%= escape_and_echo(hash.to_json) %>
```

**Comment by mwrock** [comment]
I think the main issue is that `Hash.to_json` is expected to "just work" in any recipe.

**Comment by lamont-granquist** [comment]
^ yep that's the problem.

we should eliminate all those usages of Hash.to_json internally, but we can't really remove the `require 'json'` bit.

we could consider wiring up our own monkeypatch `Hash.to_json` to FFI_Yajl, but we probably can't just drop that.

we might, though, be able to lazy the require "json" to someplace closer to where recipe parsing happens?

**Comment by mwrock** [comment]
@tas50 https://github.com/chef/knife-azure/pull/534 should help the `knife` scenario. This single `require` was eating 10 seconds.

**Comment by tas50** [comment]
Yep that one was pretty terrible. I have another issue open to change up how we use azure so we can avoid the giant include there and trim a few million lines of code.

**Comment by mwrock** [comment]
https://github.com/chef/knife-cloud/pull/140 takes another second off of knife command loading.

**Comment by mwrock** [comment]
I think we have captured all of the low hanging `autoload` fruit for chef-client and knife startup performance given a standard chef-workstation installation of plugins. I am going to reassign to @lamont-granquist for now since I believe he had some work in progress to speed up rubygems.

**Comment by mwrock** [comment]
Added https://github.com/chef/chef-workstation/issues/1505 to the checklist of this epic which would shave off ~3 seconds on any use of `chef exec` or `chef shell-init`.
