### ISSUE TITLE
Target Mode enhancements from Thomas Heinen

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#9125]
Unfortunately for now this is just a reminder to myself to extract useful information out of the e-mail that I have as the very first task.

- [x] There's some remote ohai work that needs to happen.

- [ ] There's some use-case to capture like making not_if/only_if work remotely.

- [ ] I'm not sure I'm wild about the run_resource_locally helper method since it seems like hacky way to wire up a target mode template resource, but I need to dig into the use case more (it may still be useful to include since getting work done via a hack is still getting work done, and actual file resources may be difficult).

**Comment by tas50** [comment]
Closing this one out as an epic to create a more generic investigation / execution epic
